// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvkrjsndcbztaekrsopa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2a3Jqc25kY2J6dGFla3Jzb3BhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjExNDEsImV4cCI6MjA2MDI5NzE0MX0.TMlDyVz-qVwMXA73zTR57Xx4HX01Ez8R-mMPPsQ68j8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);